services:
  - type: web
    name: dokuman-veri-cikarici
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    plan: free